# Generated by Django 4.0.5 on 2023-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('docsize1', models.FloatField(null=True)),
                ('docsize2', models.FloatField(null=True)),
                ('docsize3', models.FloatField(null=True)),
                ('docsize4', models.FloatField(null=True)),
                ('docsize5', models.FloatField(null=True)),
                ('rows', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
