# Generated by Django 4.0.5 on 2023-08-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='docsize1',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='model_name',
            new_name='end_loc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='docsize2',
            new_name='zipcode_end',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='docsize3',
            new_name='zipcode_start',
        ),
        migrations.AddField(
            model_name='project',
            name='start_loc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
