# Generated by Django 4.0.5 on 2023-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_docsize1_project_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city_end',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='city_start',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
