# Generated by Django 4.0.5 on 2023-08-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_project_city_end_project_city_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country_end',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='country_start',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='state_end',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='state_start',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
