# Generated by Django 4.2.4 on 2023-08-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_rename_country_end_project_city_between_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_loc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_loc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='zipcode_end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='zipcode_start',
        ),
    ]
